[package]
name = "katei/irb"
version = "0.1.3"
description = "Interactive Ruby"
license = "MIT"
repository = "https://github.com/kateinoigakukun/ruby.wasm"

[[module]]
name = "irb"
source = "dist/irb.wasm"
abi = "wasi"

[[command]]
name = "irb"
module = "irb"
