[package]
name = "katei/ruby"
version = "0.1.2"
description = "The Ruby Programming Language"
license = "MIT"
repository = "https://github.com/ruby/ruby.wasm"

[[module]]
name = "ruby"
source = "dist/ruby.wasm"
abi = "wasi"

[[command]]
name = "ruby"
module = "ruby"
