name: Nightly release
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  create-nightly-tag:
    runs-on: ubuntu-20.04
    outputs:
      tag-name: ${{ steps.generate-tag.outputs.name }}
    steps:
      - uses: actions/checkout@v2
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - id: generate-tag
        run: echo "::set-output name=name::$(date +'%Y-%m-%d')-a"
      - run: git tag "${{ steps.generate-tag.outputs.name }}"
      - run: git push origin "${{ steps.generate-tag.outputs.name }}"
  build-and-publish:
    needs: [create-nightly-tag]
    uses: ./.github/workflows/build.yml
    with:
      publish: true
      prerel_name: ${{ needs.create-nightly-tag.outputs.tag-name }}
